apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-node
spec:
  serviceName: "hadoop-node"
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-node
  template:
    metadata:
      labels:
        app: hadoop-node
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - hadoop-node
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hadoop-node
        image: cclient/hadoop:2.8.3-datanode
#        imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-node
  labels:
    app: hadoop-node
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: hadoop-node