---
# hive metastore
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hadoop-hive-mysql
  name: hadoop-hive-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-hive-mysql
  template:
    metadata:
      labels:
        app: hadoop-hive-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: hadoop        
        - name: HOST
          value: 0.0.0.0
        - name: TZ
          value: Asia/Shanghai
        image: 172.20.101.40:6000/mysql:5.7.33
        name: hadoop-hive-mysql
        # volumeMounts:
        # - mountPath: /var/lib/mysql
        #   name: data
        ports:
        - containerPort: 3306
      # volumes:
      # - hostPath:
      #     path: /data/pv/hadoop-hive-mysql
      #     type: ""
      #   name: data
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-hive-mysql
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: hadoop-hive-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-master
spec:
  serviceName: "hadoop-master"
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-master
  template:
    metadata:
      labels:
        app: hadoop-master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - hadoop-master
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hadoop-master
        image: 172.20.101.40:6000/cclient/hadoop:2.8.3-namenode
        imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        env:
        - name: NODES
          value: hadoop-node
        - name: HOSTNODE
          value: hadoop-master
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 8088
        - containerPort: 8042
        - containerPort: 50070
        - containerPort: 8888
        - containerPort: 8080
        - containerPort: 4040
        - containerPort: 8787
        - containerPort: 9000
        - containerPort: 60010
        - containerPort: 60030
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-master
  labels:
    app: hadoop-master
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    nodePort: 32620
    targetPort: 22
  - name: hadoop-cluster-info
    port: 8088
    nodePort: 32688
    targetPort: 8088
  - name: b
    port: 8042
    # nodePort: 8342
    targetPort: 8042
  - name: c
    port: 50030
    nodePort: 32630
    targetPort: 50030
  - name: hadoop-namenode-info
    port: 50070
    nodePort: 32670
    targetPort: 50070
  - name: jupyter-notebook
    port: 8888
    nodePort: 32488
    targetPort: 8888
  - name: e
    port: 4040
    # nodePort: 8340
    targetPort: 4040
  - name: f
    port: 8787
    # nodePort: 8387
    targetPort: 8787
  - name: g
    port: 9000
    targetPort: 9000
  - name: hbase-master-info
    port: 60010
    nodePort: 32510
    targetPort: 60010
  - name: hbase-regionserver-info
    port: 60030
    nodePort: 32530
    targetPort: 60030
  - name: hiveserver2-jdbc
    port: 10000
    nodePort: 32000
    targetPort: 10000    
  - name: hiveserver2-web
    port: 10002
    nodePort: 32002
    targetPort: 10002        
  selector:
    app: hadoop-master        
